version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: projeto-cd-db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: projeto_cd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - projeto_network

  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - projeto_network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - projeto_network

  app-usuario:
    build: ./Usuario
    container_name: projeto-usuario
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/projeto_cd
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
      JWT_SECRET: chaveSecretaMuitoSegura
    ports:
      - "8083:8080"
    networks:
      - projeto_network

  app-alunos:
    build: ./Aluno
    container_name: projeto-aluno
    depends_on:
      - postgres-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/projeto_cd
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - projeto_network

  app-professor:
    build: ./Professor
    container_name: projeto-professor
    depends_on:
      - postgres-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/projeto_cd
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8080"
    networks:
      - projeto_network

  app-tecnico-adm:
    build: ./TecnicoAdministrativo
    container_name: projeto-adm
    depends_on:
      - postgres-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/projeto_cd
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8082:8080"
    networks:
      - projeto_network

  api-gateway:
    build: ./Gateway
    container_name: projeto-gateway
    depends_on:
      - app-usuario
      - app-alunos
      - app-professor
      - app-tecnico-adm
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: usuario-service
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://app-usuario:8080
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/auth/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: aluno-service
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://app-alunos:8080
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/api/aluno/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_ID: professor-service
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://app-professor:8080
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: Path=/api/professor/**
      SPRING_CLOUD_GATEWAY_ROUTES_3_ID: tecnico-service
      SPRING_CLOUD_GATEWAY_ROUTES_3_URI: http://app-tecnico-adm:8080
      SPRING_CLOUD_GATEWAY_ROUTES_3_PREDICATES_0: Path=/api/admin/**
    ports:
      - "8088:8080"
    networks:
      - projeto_network
  
  app-gestao-turmas:
    build: ./GestaoTurmas
    container_name: projeto-gestao-turmas
    depends_on:
      - postgres-db
      - kafka
      - app-professor
      - app-alunos
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/projeto_cd
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker

      # Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8089:8080"
    networks:
      - projeto_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app-usuario
      - app-alunos
      - app-professor
      - app-tecnico-adm
    networks:
      - projeto_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - projeto_network

volumes:
  postgres_data:

networks:
  projeto_network:
    driver: bridge

